spring.profiles.active: develop
server:
  port: 8090
jwt:
  secret-key: C2x5A8B4F0E2D6G3H1J4K7L9M1N3P5R8S0T2U4V6W8Y1Z3A5B7D9G2J4L6N8R0
  expiration-ms: 3600000 # 1 hour

spring.h2.console:
  enabled: true
  path: /h2-console

---
spring.config.activate.on-profile: develop
spring:
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false
stripe.simulator.charges-uri: https://sandbox.playtomic.io/v1/stripe-simulator/charges
stripe.simulator.refunds-uri: https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds
---
spring.config.activate.on-profile: test
spring:
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false
stripe.simulator.charges-uri: http://localhost:9999
stripe.simulator.refunds-uri: http://localhost:9999